---
title: "Covid State Trends"
author: "John Morse"
date: "8/16/2020"
output:
  html_document: default
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## COVID-19 Trends by State

This file shows trends in COVID-19 daily cases and deaths by State within the US.

```{r libraries, include=FALSE}
library(tidyverse)
library(lubridate)
library(gridExtra)
library(scales)

source('covidDataCollect.R')
source('covidStatesData.R')
source('covidGraph.R')

```

```{r variables, include=FALSE}

# Define standard variables for date range
startDate <- as.Date("2020-03-01")  # default to start of data availability
endDate <- today() - 6              # End date is always day before today
#endDate <- as.Date('2020-08-10')
sCovidUSCSV <- "covidus.csv"        # default name of source file with prior data

# Identify the location of the source files
sPrefix <- "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/"
sSuffix <- ".csv"

# Define standard variables for states of interest
cStAbb <- c('WA', 'CO', 'MN', 'CA', 'MT')
cStName <- c('Washington', 'Colorado', 'Minnesota', 'California', 'Montana')

```

```{r read_file, include=FALSE}

# Call the function that reads in the CSV file
covidusFile <- readData(sCovidUSCSV)

# If we could read in a CSV file, we need to update the start date.
if (!is.null(covidusFile)) {
  # Determine the most recent date stored in the CSV file
  startDate <- max(covidusFile$Last_Update)
  
  # As a point of cleanup, we will strip out all rows associated
  # with the last date, and use that as our start date
  covidusFile <- covidusFile %>%
    filter(Last_Update != startDate)
}
# If we could not read in the file, then leave the start date as is.

```

```{r build_states, include=FALSE}

# Call the function from our DataCollect file
# to go get new data from the web
covidusNew <- getNewData(startDate, endDate, sPrefix, sSuffix)

# If we had a source file at the start, we append the new data
# to the end of the source file
if (!is.null(covidusFile)) {
  # Append the new data on to the data loaded from the CSV
  covidus <- rbind(covidusFile, covidusNew)
} else {
  # if we did not have a source file, just use what
  # we just collected as our total data set
  covidus <- covidusNew
}

# ALL State data is now in a data frame called covidus
# Write that as the new CSV file, overwriting the old
write_csv(covidus, path="covidus.csv", append=FALSE)

# Call the function from the covidStates file
# To generate State specific data
# Call the function, passing in the desired list of States
covidSt <- getStates(covidus, cStAbb, cStName)
#covidSt <- getStates(covidus)

```


### Daily Confirmed Cases

You can also embed plots, for example:

```{r daily_cases, echo=FALSE, message=FALSE, warning=FALSE}

pc <- ggplot(covidSt, aes(x = Last_Update)) +
  geom_bar(mapping = aes(y = daily_confirmed, fill=St), stat = "identity") +
  labs(title='Daily Cases', y='# Cases', x='Day') +
  geom_smooth(mapping = aes(y = daily_confirmed), se = FALSE) +
  facet_wrap(~ St, nrow=length(cStName), scales = 'free_y')
print(pc)

```


### Daily Deaths

You can also embed plots, for example:

```{r daily_deaths, echo=FALSE, message=FALSE, warning=FALSE}

pd <- ggplot(covidSt, aes(x = Last_Update)) +
  geom_bar(mapping = aes(y = daily_deaths, fill=St), stat = "identity") +
  labs(title='Daily Deaths', y='# Deaths', x='Day') +
  geom_smooth(mapping = aes(y = daily_deaths), se = FALSE) +
  facet_wrap(~ St, nrow=length(cStName), scales = 'free_y')
print(pd)

```


### Cummulative Results

You can also embed plots, for example:

```{r cumm_results, echo=FALSE, message=FALSE, warning=FALSE}

pcumm <- ggplot(covidSt, aes(x = Last_Update)) +
  scale_y_log10(breaks = 10^(0:10), labels=trans_format("log10", math_format(10^.x))) +
  geom_line(mapping = aes(y = confirmed, color=St), size=1) +
  geom_line(mapping = aes(y = deaths, color=St), size=1, linetype=2) +
  labs(title='Confirmed Cases: Cummulative', y='Total Cases (Log Scale compares Rate of increase)', x='Day')

print(pcumm)

```
